  
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer";
import PageLoader from "@/components/PageLoader";

// import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Shop Mart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <SessionProvider> */}
          <Navbar />

          <div className="container mx-auto p-3">
            <Toaster />
            {children}
 
          </div>
           <PageLoader />

          <Footer />
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}






























 