// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
//  import type { Metadata } from "next";
// import "tw-animate";  
// import "./globals.css";
// import Navbar from "@/components/Navbar/Navbar";
 

// export const metadata: Metadata = {
//   title: " shop mart",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body>
//        <Navbar/>
//         <div className="container mx-auto p-3">

//         {children}
//         </div>
//       </body>
//     </html>
//   );
// }

 
 







 
















// // app/layout.tsx
// import type { Metadata } from "next";
// import "./globals.css";
// import "tw-animate";

// import Navbar from "@/components/Navbar/Navbar";
// import PageLoader from "@/components/PageLoader";

// export const metadata: Metadata = {
//   title: "ShopMart",
//   description: "Your one-stop destination for shopping",
// };

//  export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>
//         {/* Loading Screen */}
//         <PageLoader />

//         {/* Navbar */}
//         <Navbar />

//         {/* Page Content */}
//         <div className="container mx-auto p-3">
//           {children}
//         </div>
//       </body>
//     </html>
//   );
// }















//  // app/layout
// import type { Metadata } from "next";
// import "./globals.css";
// import "tw-animate";

// import Navbar from "@/components/Navbar/Navbar";
// import PageLoader from "@/components/PageLoader";
// import { Toaster } from "react-hot-toast";
// import { SessionProvider } from "next-auth/react";
// import MainContext from "@/components/MainContext";

// // export const metadata: Metadata = {
// //   title: "ShopMart",
// //   description: "Your one-stop destination for shopping",
// // };
// .tsx
 
// i
// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body>
        
//       </body>
//     </html>
//   );
// }





























































































import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer";
import PageLoader from "@/components/PageLoader";

// import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Shop Mart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <SessionProvider> */}
          <Navbar />

          <div className="container mx-auto p-3">
            <Toaster />
            {children}
 
          </div>
           <PageLoader />

          <Footer />
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}






























 